### ISSUE TITLE
TP1

### ISSUE THREAD

**Issue by fbaglivo** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-MaxPower1995#2]
Hola! Te dejo algunos comentarios:

- Por favor agrega el diagrama circuital con la resistencia, LED, ciricuito de Reset y de clock.
- Modifica el formato del codigo para que se vea los labels en la columna 1, la instruccion en la columna 2, y los operandos en las columnas 3 y 4.
- Por favor agrega el costo estimado de los materiales que usaste.

**Comment by MaxPower1995** [comment]
@fbaglivo @pimartos @PucciFernando  Profe con respecto a que escriba el codigo en el formato indicado, tengo un problema, cuando lo paso a Latex no me respeta las tabulaciones que puse en el .asm, subo el tp con las otras correcciones y los archivos .asm corregidos con las columnas correspondientes, saludos

**Comment by MaxPower1995** [comment]
la cerre por error

**Comment by MaxPower1995** [comment]
@fbaglivo @pimartos @PucciFernando >Hola, Buenas Noches, ahí arregle las cosas, en látex no puedo dejar las tabulaciones en el código, no me los tomas. saludos

**Comment by fbaglivo** [comment]
Aprobado. Fijate que tiene que haber alguna forma de poner las tabulaciones en latex.
